package axisimski.bigramtagger

/**
 * Created by Alex on 3/7/2018.
 */

class toCyrillic {

    fun convertToCyrRU(lat: String): String {

        var cyr = lat.replace("ia".toRegex(), "я")
        cyr = cyr.replace("b".toRegex(), "б")
        cyr = cyr.replace("ch".toRegex(), "ч")
        cyr = cyr.replace("ts".toRegex(), "ц")
        cyr = cyr.replace("sh".toRegex(), "ш")
        cyr = cyr.replace("shch".toRegex(), "щ")
        cyr = cyr.replace("y".toRegex(), "ы")
        cyr = cyr.replace("iu".toRegex(), "ю")
        cyr = cyr.replace("a".toRegex(), "а")
        cyr = cyr.replace("c".toRegex(), "ц")
        cyr = cyr.replace("d".toRegex(), "д")
        cyr = cyr.replace("e".toRegex(), "е")
        cyr = cyr.replace("f".toRegex(), "ф")
        cyr = cyr.replace("g".toRegex(), "г")
        cyr = cyr.replace("h".toRegex(), "х")
        cyr = cyr.replace("i".toRegex(), "и")
        cyr = cyr.replace("j".toRegex(), "й")
        cyr = cyr.replace("k".toRegex(), "к")
        cyr = cyr.replace("l".toRegex(), "л")
        cyr = cyr.replace("m".toRegex(), "м")
        cyr = cyr.replace("n".toRegex(), "н")
        cyr = cyr.replace("o".toRegex(), "о")
        cyr = cyr.replace("p".toRegex(), "п")
        cyr = cyr.replace("q".toRegex(), "к")
        cyr = cyr.replace("r".toRegex(), "р")
        cyr = cyr.replace("s".toRegex(), "с")
        cyr = cyr.replace("t".toRegex(), "т")
        cyr = cyr.replace("u".toRegex(), "у")
        cyr = cyr.replace("v".toRegex(), "в")
        cyr = cyr.replace("w".toRegex(), "уа")
        cyr = cyr.replace("x".toRegex(), "кс")
        cyr = cyr.replace("y".toRegex(), "й")
        cyr = cyr.replace("z".toRegex(), "з")

        lat.replace("IA".toRegex(), "Я")
        cyr = cyr.replace("B".toRegex(), "Б")
        cyr = cyr.replace("CH".toRegex(), "Ч")
        cyr = cyr.replace("TS".toRegex(), "Ц")
        cyr = cyr.replace("SH".toRegex(), "Ш")
        cyr = cyr.replace("SHCH".toRegex(), "Щ")
        cyr = cyr.replace("Y".toRegex(), "Ы")
        cyr = cyr.replace("IU".toRegex(), "Ю")
        cyr = cyr.replace("A".toRegex(), "А")
        cyr = cyr.replace("C".toRegex(), "Ц")
        cyr = cyr.replace("D".toRegex(), "Д")
        cyr = cyr.replace("E".toRegex(), "Е")
        cyr = cyr.replace("F".toRegex(), "Ф")
        cyr = cyr.replace("G".toRegex(), "Г")
        cyr = cyr.replace("H".toRegex(), "Х")
        cyr = cyr.replace("I".toRegex(), "И")
        cyr = cyr.replace("J".toRegex(), "Й")
        cyr = cyr.replace("K".toRegex(), "К")
        cyr = cyr.replace("L".toRegex(), "Л")
        cyr = cyr.replace("M".toRegex(), "М")
        cyr = cyr.replace("N".toRegex(), "Н")
        cyr = cyr.replace("O".toRegex(), "О")
        cyr = cyr.replace("P".toRegex(), "П")
        cyr = cyr.replace("Q".toRegex(), "К")
        cyr = cyr.replace("R".toRegex(), "Р")
        cyr = cyr.replace("S".toRegex(), "С")
        cyr = cyr.replace("T".toRegex(), "Т")
        cyr = cyr.replace("U".toRegex(), "У")
        cyr = cyr.replace("V".toRegex(), "В")
        cyr = cyr.replace("W".toRegex(), "УА")
        cyr = cyr.replace("X".toRegex(), "КС")
        cyr = cyr.replace("Y".toRegex(), "Й")
        cyr = cyr.replace("Z".toRegex(), "З")


        return cyr
    }

    fun convertToCyrBG(lat: String): String {

        var cyr = lat.replace("a".toRegex(), "а")
        cyr = cyr.replace("b".toRegex(), "б")
        cyr = cyr.replace("ch".toRegex(), "ч")
        cyr = cyr.replace("ts".toRegex(), "ц")
        cyr = cyr.replace("sht".toRegex(), "щ")
        cyr = cyr.replace("sh".toRegex(), "ш")
        cyr = cyr.replace("iu".toRegex(), "ю")
        cyr = cyr.replace("ia".toRegex(), "я")
        cyr = cyr.replace("c".toRegex(), "ц")
        cyr = cyr.replace("d".toRegex(), "д")
        cyr = cyr.replace("e".toRegex(), "е")
        cyr = cyr.replace("f".toRegex(), "ф")
        cyr = cyr.replace("g".toRegex(), "г")
        cyr = cyr.replace("h".toRegex(), "х")
        cyr = cyr.replace("i".toRegex(), "и")
        cyr = cyr.replace("j".toRegex(), "ж")
        cyr = cyr.replace("k".toRegex(), "к")
        cyr = cyr.replace("l".toRegex(), "л")
        cyr = cyr.replace("m".toRegex(), "м")
        cyr = cyr.replace("n".toRegex(), "н")
        cyr = cyr.replace("o".toRegex(), "о")
        cyr = cyr.replace("p".toRegex(), "п")
        cyr = cyr.replace("q".toRegex(), "к")
        cyr = cyr.replace("r".toRegex(), "р")
        cyr = cyr.replace("s".toRegex(), "с")
        cyr = cyr.replace("t".toRegex(), "т")
        cyr = cyr.replace("u".toRegex(), "у")
        cyr = cyr.replace("u'".toRegex(), "ъ")
        cyr = cyr.replace("v".toRegex(), "в")
        cyr = cyr.replace("w".toRegex(), "у")
        cyr = cyr.replace("x".toRegex(), "кс")
        cyr = cyr.replace("y".toRegex(), "й")
        cyr = cyr.replace("z".toRegex(), "з")

        cyr = cyr.replace("A".toRegex(), "А")
        cyr = cyr.replace("B".toRegex(), "Б")
        cyr = cyr.replace("CH".toRegex(), "Ч")
        cyr = cyr.replace("TS".toRegex(), "Ц")
        cyr = cyr.replace("SHТ".toRegex(), "Щ")
        cyr = cyr.replace("SH".toRegex(), "Ш")
        cyr = cyr.replace("IU".toRegex(), "Ю")
        cyr = cyr.replace("IA".toRegex(), "Я")
        cyr = cyr.replace("C".toRegex(), "Ц")
        cyr = cyr.replace("D".toRegex(), "Д")
        cyr = cyr.replace("E".toRegex(), "Е")
        cyr = cyr.replace("F".toRegex(), "Ф")
        cyr = cyr.replace("G".toRegex(), "Г")
        cyr = cyr.replace("H".toRegex(), "Х")
        cyr = cyr.replace("I".toRegex(), "И")
        cyr = cyr.replace("J".toRegex(), "Ж")
        cyr = cyr.replace("K".toRegex(), "К")
        cyr = cyr.replace("L".toRegex(), "Л")
        cyr = cyr.replace("M".toRegex(), "М")
        cyr = cyr.replace("N".toRegex(), "Н")
        cyr = cyr.replace("O".toRegex(), "О")
        cyr = cyr.replace("P".toRegex(), "П")
        cyr = cyr.replace("Q".toRegex(), "К")
        cyr = cyr.replace("R".toRegex(), "Р")
        cyr = cyr.replace("S".toRegex(), "С")
        cyr = cyr.replace("T".toRegex(), "Т")
        cyr = cyr.replace("U".toRegex(), "У")
        cyr = cyr.replace("U'".toRegex(), "У")
        cyr = cyr.replace("V".toRegex(), "В")
        cyr = cyr.replace("W".toRegex(), "У")
        cyr = cyr.replace("X".toRegex(), "КС")
        cyr = cyr.replace("Y".toRegex(), "Й")
        cyr = cyr.replace("Z".toRegex(), "З")


        return cyr
    }


    //To Mongolian Cyrillic
    fun convertToCyrMO(lat: String): String {

        var cyr = lat.replace("a".toRegex(), "а")
        cyr = cyr.replace("b".toRegex(), "б")
        cyr = cyr.replace("ch".toRegex(), "ч")
        cyr = cyr.replace("ts".toRegex(), "ц")
        cyr = cyr.replace("sh".toRegex(), "ш")
        cyr = cyr.replace("shch".toRegex(), "щ")
        cyr = cyr.replace("y".toRegex(), "ы")
        cyr = cyr.replace("iu".toRegex(), "ю")
        cyr = cyr.replace("ia".toRegex(), "я")
        cyr = cyr.replace("c".toRegex(), "ц")
        cyr = cyr.replace("d".toRegex(), "д")
        cyr = cyr.replace("e".toRegex(), "е")
        cyr = cyr.replace("f".toRegex(), "ф")
        cyr = cyr.replace("g".toRegex(), "г")
        cyr = cyr.replace("h".toRegex(), "х")
        cyr = cyr.replace("i".toRegex(), "и")
        cyr = cyr.replace("j".toRegex(), "й")
        cyr = cyr.replace("k".toRegex(), "к")
        cyr = cyr.replace("l".toRegex(), "л")
        cyr = cyr.replace("m".toRegex(), "м")
        cyr = cyr.replace("n".toRegex(), "н")
        cyr = cyr.replace("o".toRegex(), "о")
        cyr = cyr.replace("p".toRegex(), "п")
        cyr = cyr.replace("q".toRegex(), "к")
        cyr = cyr.replace("r".toRegex(), "р")
        cyr = cyr.replace("s".toRegex(), "с")
        cyr = cyr.replace("t".toRegex(), "т")
        cyr = cyr.replace("u".toRegex(), "у")
        cyr = cyr.replace("v".toRegex(), "в")
        cyr = cyr.replace("w".toRegex(), "уа")
        cyr = cyr.replace("x".toRegex(), "кс")
        cyr = cyr.replace("y".toRegex(), "й")
        cyr = cyr.replace("z".toRegex(), "з")
        cyr = cyr.replace("ы".toRegex(), "y")

        cyr = cyr.replace("A".toRegex(), "А")
        cyr = cyr.replace("B".toRegex(), "Б")
        cyr = cyr.replace("CH".toRegex(), "Ч")
        cyr = cyr.replace("TS".toRegex(), "Ц")
        cyr = cyr.replace("SH".toRegex(), "Ш")
        cyr = cyr.replace("SHCH".toRegex(), "Щ")
        cyr = cyr.replace("Y".toRegex(), "Ы")
        cyr = cyr.replace("IU".toRegex(), "Ю")
        cyr = cyr.replace("IA".toRegex(), "Я")
        cyr = cyr.replace("C".toRegex(), "Ц")
        cyr = cyr.replace("D".toRegex(), "Д")
        cyr = cyr.replace("E".toRegex(), "Е")
        cyr = cyr.replace("F".toRegex(), "Ф")
        cyr = cyr.replace("G".toRegex(), "Г")
        cyr = cyr.replace("H".toRegex(), "Х")
        cyr = cyr.replace("I".toRegex(), "И")
        cyr = cyr.replace("J".toRegex(), "Й")
        cyr = cyr.replace("K".toRegex(), "К")
        cyr = cyr.replace("L".toRegex(), "Л")
        cyr = cyr.replace("M".toRegex(), "М")
        cyr = cyr.replace("N".toRegex(), "Н")
        cyr = cyr.replace("O".toRegex(), "О")
        cyr = cyr.replace("P".toRegex(), "П")
        cyr = cyr.replace("Q".toRegex(), "К")
        cyr = cyr.replace("R".toRegex(), "Р")
        cyr = cyr.replace("S".toRegex(), "С")
        cyr = cyr.replace("T".toRegex(), "Т")
        cyr = cyr.replace("U".toRegex(), "У")
        cyr = cyr.replace("V".toRegex(), "В")
        cyr = cyr.replace("W".toRegex(), "УА")
        cyr = cyr.replace("X".toRegex(), "КС")
        cyr = cyr.replace("Y".toRegex(), "Й")
        cyr = cyr.replace("Z".toRegex(), "З")
        cyr = cyr.replace("Z".toRegex(), "Ы")


        return cyr
    }

    fun convertToCyrSrb(lat: String): String {

        var cyr = lat.replace("a".toRegex(), "а")
        cyr = cyr.replace("dž".toRegex(), "џ")
        cyr = cyr.replace("nj".toRegex(), "њ")
        cyr = cyr.replace("lj".toRegex(), "љ")
        cyr = cyr.replace("n".toRegex(), "н")
        cyr = cyr.replace("š".toRegex(), "ш")
        cyr = cyr.replace("b".toRegex(), "б")
        cyr = cyr.replace("v".toRegex(), "в")
        cyr = cyr.replace("g".toRegex(), "г")
        cyr = cyr.replace("d".toRegex(), "д")
        cyr = cyr.replace("đ".toRegex(), "ђ")
        cyr = cyr.replace("e".toRegex(), "е")
        cyr = cyr.replace("ž".toRegex(), "ж")
        cyr = cyr.replace("z".toRegex(), "з")
        cyr = cyr.replace("j".toRegex(), "ј")
        cyr = cyr.replace("i".toRegex(), "и")
        cyr = cyr.replace("k".toRegex(), "к")
        cyr = cyr.replace("l".toRegex(), "л")
        cyr = cyr.replace("o".toRegex(), "о")
        cyr = cyr.replace("p".toRegex(), "п")
        cyr = cyr.replace("r".toRegex(), "р")
        cyr = cyr.replace("s".toRegex(), "с")
        cyr = cyr.replace("t".toRegex(), "т")
        cyr = cyr.replace("u".toRegex(), "у")
        cyr = cyr.replace("f".toRegex(), "ф")
        cyr = cyr.replace("h".toRegex(), "х")
        cyr = cyr.replace("c".toRegex(), "ц")
        cyr = cyr.replace("č".toRegex(), "ч")
        cyr = cyr.replace("m".toRegex(), "м")


        cyr = cyr.replace("A".toRegex(), "А")
        cyr = cyr.replace("DŽ".toRegex(), "Џ")
        cyr = cyr.replace("NJ".toRegex(), "Њ")
        cyr = cyr.replace("LJ".toRegex(), "Љ")
        cyr = cyr.replace("Š".toRegex(), "Ш")
        cyr = cyr.replace("B".toRegex(), "Б")
        cyr = cyr.replace("V".toRegex(), "В")
        cyr = cyr.replace("G".toRegex(), "Г")
        cyr = cyr.replace("D".toRegex(), "Д")
        cyr = cyr.replace("Đ".toRegex(), "Ђ")
        cyr = cyr.replace("E".toRegex(), "Е")
        cyr = cyr.replace("Ž".toRegex(), "Ж")
        cyr = cyr.replace("Z".toRegex(), "З")
        cyr = cyr.replace("J".toRegex(), "ј")
        cyr = cyr.replace("I".toRegex(), "И")
        cyr = cyr.replace("K".toRegex(), "К")
        cyr = cyr.replace("L".toRegex(), "Л")
        cyr = cyr.replace("O".toRegex(), "О")
        cyr = cyr.replace("P".toRegex(), "П")
        cyr = cyr.replace("R".toRegex(), "Р")
        cyr = cyr.replace("S".toRegex(), "С")
        cyr = cyr.replace("T".toRegex(), "Т")
        cyr = cyr.replace("U".toRegex(), "У")
        cyr = cyr.replace("F".toRegex(), "Ф")
        cyr = cyr.replace("H".toRegex(), "Х")
        cyr = cyr.replace("C".toRegex(), "Ц")
        cyr = cyr.replace("Č".toRegex(), "Ч")
        cyr = cyr.replace("N".toRegex(), "Н")
        cyr = cyr.replace("M".toRegex(), "М")

        return cyr
    }

}
